module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
    "./src/app/anima/anima.css",
  ],
  theme: {
    extend: {
      fontFamily: {
        "heading-h1": "var(--heading-h1-font-family)",
        "heading-h2": "var(--heading-h2-font-family)",
        "heading-h3": "var(--heading-h3-font-family)",
        "heading-h6": "var(--heading-h6-font-family)",
        "heading-tagline": "var(--heading-tagline-font-family)",
        "text-medium-normal": "var(--text-medium-normal-font-family)",
        "text-regular-medium": "var(--text-regular-medium-font-family)",
        "text-regular-normal": "var(--text-regular-normal-font-family)",
        "text-small-link": "var(--text-small-link-font-family)",
        "text-small-normal": "var(--text-small-normal-font-family)",
        "text-small-semi-bold": "var(--text-small-semi-bold-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: { xxlarge: "var(--xxlarge)" },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },

      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [require("tailwindcss-animate")],
  safelist: [
    'font-[number:var(--heading-h1-font-weight)]',
    'font-[number:var(--heading-h2-font-weight)]',
    'font-[number:var(--heading-h3-font-weight)]',
    'font-[number:var(--heading-tagline-font-weight)]',
    'font-[number:var(--text-medium-normal-font-weight)]',
    'font-[number:var(--text-regular-medium-font-weight)]',
    'font-[number:var(--text-regular-normal-font-weight)]',
    'font-[number:var(--text-small-link-font-weight)]',
    'font-[number:var(--text-small-normal-font-weight)]',
    'font-[number:var(--text-small-semi-bold-font-weight)]',
    'leading-[var(--heading-h1-line-height)]',
    'leading-[var(--heading-h2-line-height)]',
    'leading-[var(--heading-h3-line-height)]',
    'leading-[var(--heading-h6-line-height)]',
    'leading-[var(--heading-tagline-line-height)]',
    'leading-[var(--text-medium-normal-line-height)]',
    'leading-[var(--text-regular-medium-line-height)]',
    'leading-[var(--text-regular-normal-line-height)]',
    'leading-[var(--text-small-link-line-height)]',
    'leading-[var(--text-small-normal-line-height)]',
    'leading-[var(--text-small-semi-bold-line-height)]',
    'tracking-[var(--heading-h1-letter-spacing)]',
    'tracking-[var(--heading-h2-letter-spacing)]',
    'tracking-[var(--heading-h3-letter-spacing)]',
    'tracking-[var(--heading-h6-letter-spacing)]',
    'tracking-[var(--heading-tagline-letter-spacing)]',
    'tracking-[var(--text-medium-normal-letter-spacing)]',
    'tracking-[var(--text-regular-medium-letter-spacing)]',
    'tracking-[var(--text-regular-normal-letter-spacing)]',
    'tracking-[var(--text-small-link-letter-spacing)]',
    'tracking-[var(--text-small-normal-letter-spacing)]',
    'tracking-[var(--text-small-semi-bold-letter-spacing)]',
  ],
  darkMode: ["class"],
};
