import localFont from 'next/font/local'
import "./globals.css";


const theYoungestSerif = localFont({
  src: "../fonts/TheYoungestSerif.ttf",
  variable: "--font-primary",
  subsets: ["latin"],
});

const ttCommonsPro = localFont({
  src: "../fonts/TTCommonsPro.otf",
  variable: "--font-secondary",
  subsets: ["latin"],
});


export const metadata = {
  title: "Meridian - Consulting Partners",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="Meridian">
      <body
        className="antialiased scroll-smooth"
      >
        {children}
      </body>
    </html>
  );
}
